name: Hexo Deploy
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: checkout source
        uses: actions/checkout@v2
        with:
          ref: hexo
      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: setup hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPOY_KEY }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "sakura_ljc@163.com"
          git config --global user.name "ljc"
          npm install hexo-cli -g
          npm install
      - name: deploy
        run: |
          hexo clean
          hexo deploy
